### ISSUE TITLE
OSX 10.15

### ISSUE THREAD

**Issue by bst265** [miyako/4d-plugin-common-crypto#7] opened 2019-10-10 11:46 UTC
Hello Mijako
We use your plugin - it works great! But in Catalina i have a little Problem. When i start 4D with the plugin, following error is comming:

"Common Crypto.bundle" is damaged and can not be opened. It is best to move the item to the trash.

latest version V17 R5

do you have a idea?

thanks

bernhard

![Bildschirmfoto 2019-10-10 um 13 45 50](https://user-images.githubusercontent.com/46921988/66566064-48136b80-eb64-11e9-9d79-14cfc65c0694.png)

![Bildschirmfoto 2019-10-10 um 13 24 08](https://user-images.githubusercontent.com/46921988/66565957-05519380-eb64-11e9-9e91-d8bef5c6f62e.png)

**Comment by miyako** [comment] 2019-10-10 13:08
could you please try ``3.0`` 

https://github.com/miyako/4d-plugin-common-crypto/releases/tag/3.0

and let me know if it works?

**Comment by bst265** [comment] 2019-10-10 13:14
THANKS - this seems to work

Mit freundlichen Grüßen

Bernhard Stolz


OfficeNo1 Software Solutions GmbH
Alpenblick 5
4203 Altenberg
Österreich


Tel:   +43 699 13 42 57 69
www.officeno1.at

**Comment by miyako** [comment] 2019-10-11 04:37
by the way, you might have similar problems with qrencode.

I've updated that also.

**Comment by bst265** [comment] 2019-10-11 04:38
Thank you
Mit freundlichen Grüßen

Bernhard Stolz


OfficeNo1 Software Solutions GmbH
Alpenblick 5
4203 Altenberg
Österreich


Tel:   +43 699 13 42 57 69
www.officeno1.at

**Comment by bst265** [comment] 2019-10-11 05:18
morning

there is with 3.0 the same problem

2.0 is working ….
Mit freundlichen Grüßen

Bernhard Stolz


OfficeNo1 Software Solutions GmbH
Alpenblick 5
4203 Altenberg
Österreich


Tel:   +43 699 13 42 57 69
www.officeno1.at

**Comment by miyako** [comment] 2019-10-11 06:35
please specify which plugin you are talking about.

they are both 3.0.

and please repeat what the "same problem" is.

I can not work on such fragmented comment.

**Comment by bst265** [comment] 2019-10-11 09:57
Hello

qrencode 3.0 has the problem i wrote to you

qrencode 2.0 works


thanks


Mit freundlichen Grüßen

Bernhard Stolz


OfficeNo1 Software Solutions GmbH
Alpenblick 5
4203 Altenberg
Österreich


Tel:   +43 699 13 42 57 69
www.officeno1.at

**Comment by miyako** [comment] 2019-10-11 13:35
I am sorry but I can't reproduce the issue "plugin is broken".
it generally means the code signature is invalid.
can you send me a simply structure that reproduces the problem?

**Comment by miyako** [comment] 2019-10-11 15:58
I am going to close this case, as it concerns a different repository.

**Comment by bst265** [comment] 2019-10-11 16:56
hello

when you start this (4D V17 R5) you get the message

thanks


Mit freundlichen Grüßen

Bernhard Stolz


OfficeNo1 Software Solutions GmbH
Alpenblick 5
4203 Altenberg
Österreich


Tel:   +43 699 13 42 57 69
www.officeno1.at

**Comment by miyako** [comment] 2019-10-11 17:14
I am sorry but I do not get such dialog on my side,
which is why I keep asking for more details. (another user says it's ok on catalina too)

and please open an issue on the other repository if common-crypto is not the issue.

**Comment by miyako** [comment] 2019-10-12 00:26
for what it's worth, I've slightly changed the code signature in qrencode 3.2
https://github.com/miyako/4d-plugin-qrencode/releases/tag/3.2

I also posted a v2 which is not backward compatible, but support native objects and collections.
https://github.com/miyako/4d-plugin-qrencode-v2

**Comment by miyako** [comment] 2019-10-16 07:56
I've notarized the plugin in 3.2 
https://github.com/miyako/4d-plugin-common-crypto/releases/tag/3.2
does this make a change?

**Comment by bst265** [comment] 2019-10-16 08:05
This works - thanks
Mit freundlichen Grüßen

Bernhard Stolz


OfficeNo1 Software Solutions GmbH
Alpenblick 5
4203 Altenberg
Österreich


Tel:   +43 699 13 42 57 69
www.officeno1.at

**Closed as completed** 2019-10-16 09:00 UTC
